services:
  # Service Web Symfony
  - type: web
    name: wr506d-api
    runtime: php
    plan: starter
    buildCommand: chmod +x .render-build.sh && ./.render-build.sh
    startCommand: php -S 0.0.0.0:$PORT -t public public/index.php
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: wr506d-db
          property: connectionString
      - key: MESSENGER_TRANSPORT_DSN
        value: doctrine://default?auto_setup=0
      - key: MAILER_DSN
        value: null://null
      - key: CORS_ALLOW_ORIGIN
        value: '^https?://(.*\.render\.com|localhost|127\.0\.0\.1)(:[0-9]+)?$'
      - key: JWT_SECRET_KEY
        value: '%kernel.project_dir%/config/jwt/private.pem'
      - key: JWT_PUBLIC_KEY
        value: '%kernel.project_dir%/config/jwt/public.pem'
      - key: JWT_PASSPHRASE
        generateValue: true
    healthCheckPath: /api/docs

  # Base de donn√©es MySQL
  - type: mysql
    name: wr506d-db
    plan: starter
    databaseName: symfony
    databaseUser: symfony

  # phpMyAdmin
  - type: web
    name: wr506d-phpmyadmin
    runtime: docker
    dockerfilePath: ./Dockerfile.phpmyadmin
    envVars:
      - key: PMA_HOST
        fromService:
          name: wr506d-db
          type: mysql
          property: host
      - key: PMA_PORT
        fromService:
          name: wr506d-db
          type: mysql
          property: port
      - key: PMA_USER
        fromService:
          name: wr506d-db
          type: mysql
          property: user
      - key: PMA_PASSWORD
        fromService:
          name: wr506d-db
          type: mysql
          property: password
      - key: UPLOAD_LIMIT
        value: '50M'
    plan: starter
